IAC = "INSERT INTO AC VALUES ('{}' , '{}' , '{}' , '{}' , {} , {} , '{}');"
IFR = "INSERT INTO FRIDGES VALUES ('{}' , '{}' , '{}' , '{}' , {} , {} , '{}');"
IKA = "INSERT INTO K_APPS VALUES ('{}' , '{}' , '{}' , '{}' , {} , {});"
ITV = "INSERT INTO TV VALUES ('{}' , '{}' , '{}' , {} , {} , {} , '{}');"
IWS = "INSERT INTO WSH_MCH VALUES ('{}' , '{}' , '{}' , '{}' , {} , '{}' , {} , '{}');"