IAC = "INSERT INTO AC VALUES ('{}' , '{}' , '{}' , '{}' , {} , {} , '{}');"
IFR = "INSERT INTO FRIDGES VALUES ('{}' , '{}' , '{}' , '{}' , {} , {} , '{}');"
IKA = "INSERT INTO K_APPS VALUES ('{}' , '{}' , '{}' , '{}' , {} , {});"
ITV = "INSERT INTO TV VALUES ('{}' , '{}' , '{}' , {} , {} , {} , '{}');"
IWS = "INSERT INTO WSH_MCH VALUES ('{}' , '{}' , '{}' , '{}' , {} , '{}' , {} , '{}');"
CAC1 = "SELECT * FROM AC WHERE Product_ID LIKE '{}';"
CFR1 = "SELECT * FROM FRIDGES WHERE Product_ID LIKE '{}';"
CKA1 = "SELECT * FROM K_APPS WHERE Product_ID LIKE '{}';"
CTV1 = "SELECT * FROM TV WHERE Product_ID LIKE '{}';"
CWS1 = "SELECT * FROM WSH_MCH WHERE Product_ID LIKE '{}';"
CAC2 = "SELECT * FROM AC WHERE Company LIKE '{}';"
CFR2 = "SELECT * FROM FRIDGES WHERE Company LIKE '{}';"
CKA2 = "SELECT * FROM K_APPS WHERE Company LIKE '{}';"
CTV2 = "SELECT * FROM TV WHERE Company LIKE '{}';"
CWS2 = "SELECT * FROM WSH_MCH WHERE Company LIKE '{}';"
CAC3 = "SELECT * FROM AC WHERE Colour LIKE '{}';"
CFR3 = "SELECT * FROM FRIDGES WHERE Colour LIKE '{}';"
CKA3 = "SELECT * FROM K_APPS WHERE Type LIKE '{}';"
CTV3 = "SELECT * FROM TV WHERE Size LIKE {};"
CWS3 = "SELECT * FROM WSH_MCH WHERE Colour LIKE '{}';"
CWS4 = "SELECT * FROM WSH_MCH WHERE Type LIKE '{}';"
PAC = "SELECT Company , Model , Price , Colour FROM AC WHERE Product_ID LIKE '{}';"
PFR = "SELECT Company , Model , Price , Colour FROM FRIDGES WHERE Product_ID LIKE '{}';"
PKA = "SELECT Company , Name , Price FROM K_APPS WHERE Product_ID LIKE '{}';"
PTV = "SELECT Company , Name , Price FROM TV WHERE Product_ID LIKE '{}';"
PWS = "SELECT Company , Model , Price , Colour FROM WSH_MCH WHERE Product_ID LIKE '{}';"
UAC = "UPDATE AC SET Pieces = Pieces - {} WHERE Product_ID LIKE '{}';"
UFR = "UPDATE FRIDGES SET Pieces = Pieces - {} WHERE Product_ID LIKE '{}';"
UKA = "UPDATE K_APPS SET Pieces = Pieces - {} WHERE Product_ID LIKE '{}';"
UTV = "UPDATE TV SET Pieces = Pieces - } WHERE Product_ID LIKE '{}';"
UWS = "UPDATE WSH_MCH SET Pieces = Pieces - {} WHERE Product_ID LIKE '{}';"